### ISSUE TITLE
The method of installing on Centos

### ISSUE THREAD

**Issue by SomeBottle** [MCPI-Devs/proxy#6]
```
yum  -y install  alien   
alien -r mcpi-proxy_0.3.2.deb generated   
```
Use alien to generate a rpm pakage , and then:  
```
rpm  -ivh  --nodeps  --force  mcpi-proxy-0.3.2-2.noarch.rpm  
```

**Comment by mobilegmYT** [comment]
> ```
> yum  -y install  alien   
> alien -r mcpi-proxy_0.3.2.deb generated   
> ```
> 
> Use alien to generate a rpm pakage , and then:
> 
> ```
> rpm  -ivh  --nodeps  --force  mcpi-proxy-0.3.2-2.noarch.rpm  
> ```

Oh nice! This should work for all arch based OSes right?

**Comment by NoozAbooz** [comment]
Added with commit https://github.com/MCPI-Revival/proxy/commit/8bed3d73e8853cc82d31ac79678b54a48183e7b5
